version: '3'

services:
  mangopost_nextjs:
    image: alekszejg/mangopost:latest
   

  nginx:
    container_name: nginx 
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - mangopost_nextjs
